# Product State Template
# Copy to: products/[product-name]/.claude/state.yml
# Auto-managed by Orchestrator agents working on this product

product:
  name: "[product-name]"
  created_at: "[timestamp]"

# Lifecycle phase
# inception → architecture → development → testing → production
phase: inception
status: active  # active | paused | completed | cancelled

# Current sprint/milestone
current_sprint: "1.0"
current_milestone: null

# Tech stack (filled during architecture)
tech_stack:
  backend: null
  frontend: null
  database: null
  testing: null

# Active tasks for THIS product only
active_tasks: []
  # Example:
  # - id: "TASK-001"
  #   agent: "backend-engineer"
  #   description: "Implement user registration"
  #   status: in_progress
  #   branch: "feature/product/user-registration"
  #   started: "2025-01-25T00:00:00Z"

# Pending decisions for THIS product
pending_decisions: []
  # Example:
  # - id: 1
  #   question: "Which auth provider?"
  #   options: ["Auth0", "Clerk", "Custom JWT"]
  #   raised_by: "architect"
  #   raised_at: "2025-01-25T00:00:00Z"

# Checkpoints awaiting CEO approval
checkpoints: []
  # Example:
  # - id: 1
  #   type: feature_complete
  #   title: "Auth feature ready"
  #   pr_number: 5
  #   raised_at: "2025-01-25T00:00:00Z"

# Agent activity on THIS product
agent_activity:
  product-manager:
    last_task: null
    last_activity: null
  architect:
    last_task: null
    last_activity: null
  backend-engineer:
    last_task: null
    last_activity: null
  frontend-engineer:
    last_task: null
    last_activity: null
  qa-engineer:
    last_task: null
    last_activity: null
  devops-engineer:
    last_task: null
    last_activity: null

# Recent errors on THIS product
error_log: []

# Last updated timestamp
last_updated: "[timestamp]"
