# Template for product-specific production deployment
# Copy this to .github/workflows/deploy-production-[product-name].yml and customize

name: Deploy [Product Name] to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., v1.2.3)'
        required: true
        type: string
      product:
        description: 'Product to deploy'
        required: true
        default: '[product-name]'
        type: string

env:
  PRODUCT_PATH: products/${{ inputs.product }}
  PRODUCT_NAME: ${{ inputs.product }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}

      - name: Validate version tag
        env:
          VERSION: ${{ inputs.version }}
        run: |
          if ! git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "Error: Version $VERSION does not exist"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ env.PRODUCT_PATH }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.PRODUCT_PATH }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.PRODUCT_PATH }}
        env:
          NEXT_PUBLIC_API_URL: ${{ vars.API_URL }}

      - name: Backup database
        run: |
          echo "Creating database backup before deployment..."
          # Add your backup command here
          # Example: pg_dump $DATABASE_URL > backup-$(date +%Y%m%d-%H%M%S).sql
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run migrations
        run: npm run db:migrate:deploy
        working-directory: ${{ env.PRODUCT_PATH }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Uncomment and configure for your deployment target

      # - name: Deploy to production
      #   run: |
      #     # Your deployment commands here
      #     echo "Deploying ${{ env.PRODUCT_NAME }} version ${{ inputs.version }}"

      - name: Wait for deployment
        run: sleep 90

      - name: Health check
        run: |
          for i in 1 2 3 4 5; do
            if curl -f ${{ vars.API_URL }}/health; then
              echo "Health check passed"
              exit 0
            fi
            echo "Attempt $i failed, retrying..."
            sleep 10
          done
          echo "Health check failed after 5 attempts"
          exit 1

      - name: Smoke test
        run: |
          curl -f ${{ vars.WEB_URL }} || exit 1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ env.PRODUCT_NAME }} ${{ inputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rollback:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    environment: production

    steps:
      - name: Rollback notification
        run: |
          echo "Deployment failed! Manual rollback may be required."
          echo "Check the deployment logs and consider rolling back to the previous version."
          # Add notification to Slack/Discord/Email here
